#
# Copyright (c) 2018 Bosch Software Innovations GmbH and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
version: '3.7'

services:

  # ---------------------
  # hawkBit service
  # ---------------------
  hawkbit:
    image: "hawkbit/hawkbit-update-server:latest-mysql"
    networks:
    - hawknet
    ports:
    - "8443:8443"
    deploy:
      restart_policy:
        condition: on-failure
    environment:
    - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hawkbit'
    - 'SPRING_DATASOURCE_USERNAME=root'
    - 'SPRING_RABBITMQ_HOST=rabbitmq'
    - 'SPRING_RABBITMQ_USERNAME=guest'
    - 'SPRING_RABBITMQ_PASSWORD=guest'
    - 'HAWKBIT_ARTIFACT_URL_PROTOCOLS_DOWNLOAD-HTTP_PROTOCOL=https'
    - 'HAWKBIT_ARTIFACT_URL_PROTOCOLS_DOWNLOAD-HTTP_PORT=8443'
    - 'SECURITY_REQUIRE-SSL=true'
    - 'SERVER_USE-FORWARD-HEADERS=true'
    - 'SERVER_PORT=8443'
    - 'SERVER_SSL_KEY-STORE=file:/opt/hawkbit/data/keystore.jks'

    env_file:
    - .env-passwords
    
    volumes: 
    - /opt/hawkbit/data:/opt/hawkbit/data



  # ---------------------
  # RabbitMQ service
  # ---------------------
  rabbitmq:
    image: "rabbitmq:3-management"
    networks:
    - hawknet
    ports:
    - "15672:15672"
    - "5672:5672"
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"

  # ---------------------
  # MySQL service
  # ---------------------
  mysql:
    image: "mysql:5.7"
    networks:
    - hawknet
    ports:
    - "3306:3306"
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_DATABASE: "hawkbit"
      MYSQL_USER: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"


networks:
  hawknet:
    driver: overlay
